//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMTS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public int Id { get; set; }
        public string LocationName { get; set; }
    
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
