//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMTS_WebApi.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    public partial class User
    {
        public User()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string Password { get; set; }
        public string Mobile { get; set; }
        public bool IsAdmin { get; set; }


        [JsonIgnore]
        [IgnoreDataMember]
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
